# -*- coding: utf-8 -*-
"""Copy of Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0EWczUIUo5A-8mUnWPYhA-vQG-zUQs0

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Herlianeka Pratiwi
- **Email:** cdcc180d6x0993@student.devacademy.id
- **ID Dicoding:** CDCC180D6X0993

## Menentukan Pertanyaan Bisnis

- Seberapa kuat korelasi antara suhu (TEMP) dan PM2.5, dan apakah nilai korelasi tersebut konsisten (|r| > 0.5) selama periode 2013–2017?
- Pada jam berapa rata-rata PM2.5 tertinggi terjadi, dan apakah pola tersebut konsisten di lebih dari 70% hari selama periode 2013–2017?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# Load data
data = 'https://drive.google.com/uc?export=download&id=1Y4_St2-f9NZ9QnRRrr4sGr0vUtOyf_l2'
df = pd.read_csv(data)

# Menampilkan 5 baris pertama
df.head()

"""**Insight:**
- Dataset berisi data kualitas udara per jam dengan variabel polutan dan cuaca
- Ditemukan beberapa missing values pada kolom SO2, NO2, CO, dan O3
- Nilai PM2.5 dan PM10 relatif serupa pada beberapa observasi awal
- Suhu bernilai negatif, menunjukkan data kemungkinan diambil pada musim dingin
- Data memiliki format time series karena terdapat variabel tahun, bulan, hari, dan jam

### Assessing Data
"""

# Tinjau jumlah baris kolom dan jenis data dalam dataset
df.info()

# Mengecek data apakah terdapat missing value
df.isnull().sum()

# Mengecek duplikasi data
df.duplicated().sum()

"""**Insight:**
- Sejalan dengan insgiht sebelumnya, bahwa terdapat missing value. Bisa dilihat dari ouput diatas, total missing value pada beberapa kolom.
- Data tidak ada yang duplikat

### Cleaning Data
"""

# Data cleaning menggunakan interpolation untuk data numerik
num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = df[num_cols].interpolate(method = 'linear')

# Save dataset yang sudah bersih
df.to_csv('data_suhu_clean.csv', index=False)

# Menampilkan 5 baris pertama untuk verfikasi
df.head()

"""**Insight:**
- Karena dataset berbentuk time series, maka untuk mengatasi missing value kita gunakan metode interpolasi
- Interpolasi dilakukan pada data numerik

## Exploratory Data Analysis (EDA)

### Explorasi Parameter Statistik dari Data
"""

df.describe(include="all")

"""**Insight:**
- Mean dari Rain = 0.064285
- 50 % dari data Rain (Median) = 0.00
- 75 % dari data Rain = 0.00
Artinya, dataset didominasi kering

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

plt.scatter(df['TEMP'], df['PM2.5'])
plt.xlabel('Temperatur')
plt.ylabel('PM2.5')
plt.title('Korelasi antara TEMP vs PM2.5')
plt.show()

def hitung_korelasi(x):
  return x['TEMP'].corr(x['PM2.5'])

# Korelasi antara TEMP vs PM2.5 secara keseluruhan
overall_corr = hitung_korelasi(df)
print("Korelasi antara TEMP vs PM2.5: ", overall_corr)

# Korelasi antara TEMP vs PM2.5 per Tahun
year_corr = df.groupby('year').apply(hitung_korelasi)
print("\nKorelasi antara TEMP vs PM2.5 per Tahun:\n", year_corr)

# Menjawab pertanyaan 1:
r_corr = year_corr.abs() > 0.5
print("\n", r_corr)

"""**Insight:**
- Korelasi antara TEMP dan PM2.5 bernilai negatif, artinya ketika suhu naik konsentrasi PM2.5 cenderung turun
- Tidak ada satupun tahun yang korelasinya mencapai 0.5

### Pertanyaan 2:
"""

mean_hour = df.groupby('hour')['PM2.5'].mean()
plt.plot(mean_hour.index, mean_hour.values)
plt.xlabel('Jam')
plt.ylabel('Rata-rata PM2.5')
plt.title('Rata-rata PM2.5 per Jam')
plt.show()

peak_hour = mean_hour.idxmax()
peak_value = mean_hour.max()
print("\nJam Tertinggi:", peak_hour)
print("Nilai PM2.5:", peak_value)

# Cek Kosnsitensi di 70%
df['date'] = pd.to_datetime(df[['year','month','day']])
def ambil_jam_puncak(group):
    idx = group['PM2.5'].idxmax()
    return group.loc[idx, 'hour']

daily_peak_hour = df.groupby('date').apply(ambil_jam_puncak)
consistency = (daily_peak_hour == peak_hour).mean()

print("Konsistensi:", consistency * 100)

"""**Insight:**
- Jam rata-rata PM2.5 tertinggi = 21.00 dengan konsentrasi sebesar 95.91
- Konsistensi tidak mencapai 70% hanya mencapai 7.73%

## Conclusion

- Korelasi antara temperatur (TEMP) dan PM2.5 bersifat negatif namun sangat lemah (|r| < 0.5) dan tidak konsisten antar tahun. Hal ini menunjukkan bahwa temperatur bukan faktor utama yang memengaruhi tingkat polusi udara
- Rata-rata PM2.5 tertinggi terjadi pada malam hari (sekitar pukul 21:00), namun pola ini tidak konsisten, karena hanya terjadi pada sekitar 7-8% per hari
"""